
services:
  app:
    build: .
    command: python -u mysimbdp-dataingest.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  mongodb1:
      image: mongo:4.2.8
      ports:
        - 27017:27017
      expose:
        - 27017
      command: mongod --replSet rs0 
      hostname: mongodb1
      volumes:
        - mongodb1:/data/db
  mongodb2:
    image: mongo:4.2.8
    ports:
      - 27018:27017
    expose:
        - 27017
    command: mongod --replSet rs0 
    hostname: mongodb2
    volumes:
      - mongodb2:/data/db
  mongodb3:
    image: mongo:4.2.8
    ports:
      - 27019:27017
    expose:
        - 27017
    command: mongod --replSet rs0 
    hostname: mongodb3
    volumes:
      - mongodb3:/data/db

volumes:
  mongodb1:
  mongodb2:
  mongodb3: